import Link from "next/link";
import { requireSession, companyOf } from "@/server/auth";
import { supplierLeads } from "@/server/services/leads";
import { prisma } from "@/server/db";
import { Badge, Dt, Flash, Money } from "@/components/ui";
import { leadAction } from "@/server/actions/supplier";
import { L } from "@/lib/i18n";

export default async function Leads({ searchParams }: { searchParams: Promise<{ error?: string; ok?: string }> }) {
  const s = await requireSession(); const sp = await searchParams; const c = companyOf(s);
  const [leads, company, wallet, pitches] = await Promise.all([supplierLeads(c.id), prisma.company.findUniqueOrThrow({ where: { id: c.id } }), prisma.wallet.findUnique({ where: { company_id: c.id } }), prisma.supplierPitch.findMany({ where: { company_id: c.id }, include: { project: true, category: true }, orderBy: { created_at: "desc" }, take: 10 })]);
  // категории компании, требующие лицензию, без действующей verified-лицензии → заявки по ним не приходят
  const myCats = await prisma.category.findMany({ where: { id: { in: (company.categories_json as string[]) ?? [] }, required_license: true } });
  const licensed = await prisma.verification.findMany({ where: { company_id: c.id, doc_type: "license", status: "verified", OR: [{ valid_until: null }, { valid_until: { gt: new Date() } }] } });
  const pendingLic = await prisma.verification.findMany({ where: { company_id: c.id, doc_type: "license", status: "pending" } });
  const unlicensed = myCats.filter((k) => !licensed.some((v) => v.category_id === k.id));
  const todayStart = new Date(); todayStart.setHours(0, 0, 0, 0);
  const today = leads.filter((l) => l.created_at >= todayStart && ["matched", "rematch", "dispatcher"].includes(l.origin)).length;
  return <div><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h1 className="h1">Лиды — {company.name}</h1><p className="muted">Баланс: <Money v={wallet?.balance} /> · нагрузка сегодня {today}/{company.daily_lead_limit}{company.soft_banned_until && company.soft_banned_until > new Date() ? <span className="text-red-700"> · ⚠ soft-ban до {company.soft_banned_until.toLocaleDateString("ru-RU")}: {company.soft_ban_reason}</span> : ""}</p></div><Link href="/supplier/settings" className="btn-secondary">Настройки и лимиты</Link></div><Flash sp={sp} />
    <p className="mb-3 rounded bg-slate-100 p-2 text-sm text-slate-700">Лид — это заявка заказчика по вашей категории и зоне. Покупка лида (списывается с баланса) открывает адрес объекта, чат с заказчиком и отправку коммерческого предложения (КП). Заявки, где заказчик выбрал вас сам или сделал рассылку, — бесплатны.</p>
    {unlicensed.length > 0 && <p className="mb-3 rounded bg-amber-50 p-2 text-sm text-amber-900">Категории «{unlicensed.map((k) => k.name).join("», «")}» требуют лицензию. {pendingLic.length ? "Ваша лицензия на проверке у администратора — до подтверждения заявки этих категорий вам не поступают." : "Загрузите лицензию в настройках — до её подтверждения заявки этих категорий вам не поступают."} <Link className="underline" href="/supplier/settings">Настройки → Верификация</Link></p>}
    <div className="card"><table className="table"><thead><tr><th>Заявка</th><th>Объект</th><th>Источник</th><th>Цена лида</th><th>Статус</th><th>КП</th><th>Действия</th></tr></thead><tbody>{leads.map((l) => { const o = l.request.offers[0]; return <tr key={l.id}><td><Link className="text-brand-600" href={`/requests/${l.request_id}`}>{l.request.category.name}</Link><div className="text-xs text-slate-400"><Dt d={l.created_at} /> · заявка <Badge s={l.request.status} /></div></td><td>{l.request.project.city}{l.request.project.district ? ", " + l.request.project.district : ""} · {L(l.request.project.object_type)}{l.status === "purchased" ? <div className="text-xs">{l.request.project.name} · {l.request.project.address}</div> : <div className="text-xs text-slate-400">адрес после покупки</div>}</td><td>{L(l.origin)}</td><td><Money v={l.price} /></td><td><Badge s={l.status} /></td><td>{o ? <><Badge s={o.status} /> <Money v={o.total} /></> : "—"}</td>
      <td className="flex flex-wrap gap-1">{l.status === "offered" && <form action={leadAction} className="flex gap-1"><input type="hidden" name="lead_id" value={l.id} /><button className="btn-primary text-xs" name="action" value="purchase">Купить</button><button className="btn-secondary text-xs" name="action" value="decline">Отказаться</button></form>}
        {l.status === "purchased" && ["published", "needs_dispatcher"].includes(l.request.status) && (!o || o.status === "sent") && <Link href={`/supplier/offers/new?request=${l.request_id}`} className="btn-primary text-xs">{o ? "Новая версия КП" : "Отправить КП"}</Link>}
        {l.status === "purchased" && l.price.gt(0) && !o && <form action={leadAction} className="flex gap-1"><input type="hidden" name="lead_id" value={l.id} /><input type="hidden" name="reason" value="некорректная заявка" /><button className="btn-secondary text-xs" name="action" value="dispute" title="Если заявка некорректная или дубль — попросить администратора вернуть деньги за лид">Запросить возврат</button></form>}</td></tr>; })}</tbody></table>{!leads.length && <p className="muted">Заявок пока нет. Они приходят автоматически, когда заказчик публикует заявку по вашим категориям в вашей зоне обслуживания{unlicensed.length ? " (и подтверждена лицензия)" : ""}. Пока ждёте — посмотрите <Link className="text-brand-600" href="/supplier/map">карту объектов</Link>: там можно самому предложить услуги.</p>}</div>
    <div className="card mt-4"><h2 className="h2 mb-2">Мои встречные предложения</h2><table className="table"><tbody>{pitches.map((p) => <tr key={p.id}><td>{p.project.name}</td><td>{p.category.name}</td><td><Badge s={p.status} /></td><td className="muted">до <Dt d={p.expires_at} /></td></tr>)}</tbody></table>{!pitches.length && <p className="muted">Нет — см. <Link className="text-brand-600" href="/supplier/map">карту объектов</Link>.</p>}</div></div>;
}
