import { requireSession, companyOf } from "@/server/auth";
import { prisma } from "@/server/db";
import { Badge, Dt, Field, Flash, FileLink } from "@/components/ui";
import { companySettingsAction, verificationUploadAction, offerTemplateDeleteAction } from "@/server/actions/supplier";
import { FileInput } from "@/components/file-input";
import { config } from "@/server/config";

export default async function SupplierSettings({ searchParams }: { searchParams: Promise<{ error?: string; ok?: string }> }) {
  const s = await requireSession(); const sp = await searchParams; const c = companyOf(s);
  const regionsList = await prisma.region.findMany({ orderBy: { name: "asc" } });
  const [company, cats, templates] = await Promise.all([prisma.company.findUniqueOrThrow({ where: { id: c.id }, include: { verifications: true, members: { include: { user: true } } } }), prisma.category.findMany({ orderBy: { order_index: "asc" } }), prisma.offerTemplate.findMany({ where: { company_id: c.id }, include: { category: true } })]);
  const mine = (company.categories_json as string[]) ?? [];
  return <div className="mx-auto max-w-4xl space-y-4"><h1 className="h1">Настройки компании — {company.name}</h1><Flash sp={sp} />
    <form action={companySettingsAction} className="card grid gap-3 sm:grid-cols-2"><Field label="Описание"><textarea className="input sm:col-span-2" name="description" rows={2} defaultValue={company.description ?? ""} /></Field><Field label="Банковский счёт"><input className="input" name="bank_account" defaultValue={company.bank_account ?? ""} /></Field>
      <Field label="daily_lead_limit (лидов движка в день)"><input className="input" name="daily_lead_limit" type="number" defaultValue={company.daily_lead_limit} /></Field><Field label="pitch_daily_limit"><input className="input" name="pitch_daily_limit" type="number" defaultValue={company.pitch_daily_limit} /></Field><Field label="pitch_cooldown_days"><input className="input" name="pitch_cooldown_days" type="number" defaultValue={company.pitch_cooldown_days} /></Field>
      <div className="grid grid-cols-3 gap-1"><Field label="Центр, широта"><input className="input" name="service_center_lat" defaultValue={company.service_center_lat ?? ""} /></Field><Field label="долгота"><input className="input" name="service_center_lng" defaultValue={company.service_center_lng ?? ""} /></Field><Field label="Радиус, км"><input className="input" name="service_radius_km" defaultValue={company.service_radius_km ?? ""} /></Field></div>
      <Field label="Полигон зоны обслуживания, JSON [[lat,lng],…]" hint="Проверка пересечения — point-in-polygon + haversine (без PostGIS)"><textarea className="input" name="service_area_polygon" rows={2} defaultValue={company.service_area_polygon ? JSON.stringify(company.service_area_polygon) : ""} /></Field>
      <Field label="Коридор перевозчика (для категории «Перевозки»)" hint={`Пары кодов регионов, по одной в строке: almaty-kaskelen. Коды: ${regionsList.map((r) => r.code).join(", ")}`}><textarea className="input" name="service_routes" rows={3} defaultValue={((company.service_route_json as string[][]) ?? []).map((p) => p.join("-")).join("\n")} /></Field>
      <div className="sm:col-span-2"><label className="label">Категории (scope)</label><div className="grid grid-cols-2 gap-1 text-sm sm:grid-cols-3">{cats.map((k) => <label key={k.id}><input type="checkbox" name="categories" value={k.id} defaultChecked={mine.includes(k.id)} /> {k.name}{k.required_license ? " 🪪" : ""}</label>)}</div></div>
      <label className="text-sm"><input type="checkbox" name="is_public" defaultChecked={company.is_public} /> Показывать в публичном каталоге</label><div><button className="btn-primary">Сохранить</button></div></form>
    <div className="card"><h2 className="h2 mb-2">Верификация документов и лицензий</h2><table className="table"><tbody>{company.verifications.map((v) => <tr key={v.id}><td>{v.doc_type} <FileLink url={v.doc_url} label="файл" /></td><td>{cats.find((k) => k.id === v.category_id)?.name ?? "—"}</td><td><Badge s={v.status} /></td><td>до <Dt d={v.valid_until} />{v.valid_until && v.valid_until < new Date(Date.now() + 30 * 86400000) ? <span className="text-amber-700"> · истекает</span> : null}</td></tr>)}</tbody></table>
      <form action={verificationUploadAction} className="mt-2 grid gap-2 sm:grid-cols-5"><select className="input" name="doc_type"><option value="license">лицензия</option><option value="attestation">аттестат</option><option value="bin">БИН</option><option value="registration">регистрация</option></select><select className="input" name="category_id"><option value="">категория —</option>{cats.filter((k) => k.required_license || k.required_attestation).map((k) => <option key={k.id} value={k.id}>{k.name}</option>)}</select><FileInput name="doc" accept=".pdf,.jpg,.jpeg,.png,.webp" required maxMb={config.uploadEffectiveMaxMb} className="text-xs" /><input className="input" name="valid_until" type="date" title="Срок действия" /><button className="btn-secondary">Отправить на проверку</button></form>
      <p className="mt-1 text-xs text-slate-400">Файл до {config.uploadEffectiveMaxMb} МБ (PDF/JPG/PNG). Лицензия привязывается к категории; после подтверждения администратором заявки этой категории начнут поступать.</p></div>
    <div className="card"><h2 className="h2 mb-2">Шаблоны КП</h2>{templates.map((t) => <form key={t.id} action={offerTemplateDeleteAction} className="flex items-center justify-between border-t border-slate-100 py-1 text-sm"><span><b>{t.name}</b> · {t.category.name}</span><input type="hidden" name="id" value={t.id} /><button className="btn-secondary text-xs">удалить</button></form>)}{!templates.length && <p className="muted">Сохраняйте шаблон при отправке КП.</p>}</div>
    <div className="card text-sm"><h2 className="h2 mb-1">Сотрудники</h2><ul>{company.members.map((m) => <li key={m.user_id}>{m.user.name ?? m.user.phone} — {m.permission}</li>)}</ul></div></div>;
}
