import Link from "next/link";
import { requireSession } from "@/server/auth";
import { getDeal } from "@/server/services/deals";
import { checklistGate, computePenalty } from "@/server/services/escrow";
import { prisma } from "@/server/db";
import { Badge, Dt, Field, Flash, Money } from "@/components/ui";
import * as D from "@/server/actions/deals";
import { L } from "@/lib/i18n";
import { config } from "@/server/config";

export default async function DealPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; ok?: string }> }) {
  const { id } = await params; const sp = await searchParams; const s = await requireSession();
  const { deal, isBuyer, isSeller, isAdmin, isSupervisor } = await getDeal(id, s.user.id);
  const gates = Object.fromEntries(await Promise.all(deal.milestones.map(async (m) => [m.id, await checklistGate(m.id)] as const)));
  const myReview = deal.reviews.find((r) => r.author_id === s.user.id);
  const buyer = await prisma.user.findUniqueOrThrow({ where: { id: deal.buyer_id } });
  const activeDisputes = deal.disputes.filter((d) => ["open", "in_review"].includes(d.status));
  return <div><Flash sp={sp} />
    <div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h1 className="h1">Сделка: {deal.request.category.name} <Badge s={deal.status} /></h1><p className="muted"><Link className="text-brand-600" href={`/requests/${deal.request_id}`}>заявка</Link> · объект «{deal.request.project.name}» · исполнитель <Link className="text-brand-600" href={`/catalog/${deal.seller.public_slug}`}>{deal.seller.name}</Link> · заказчик {buyer.name ?? buyer.phone}</p></div>
      <div className="text-right"><div className="text-2xl font-bold"><Money v={deal.amount} /></div><div className="muted">комиссия {deal.commission_percent.toString()}% = <Money v={deal.commission_amount} />{deal.penalty_amount.gt(0) ? <> · пеня <Money v={deal.penalty_amount} /></> : null}</div><div className="text-xs text-slate-400">Отмена: {L(deal.cancel_policy)}{deal.work_started_at ? " · работы начаты" : ""}</div></div></div>
    {activeDisputes.length > 0 && <p className="mb-3 rounded bg-red-50 p-2 text-sm text-red-800">⚠ Активный спор — раскрытие эскроу по спорному этапу заблокировано на бэкенде до решения.</p>}
    <div className="grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
      <div className="card"><h2 className="h2 mb-2">Что входит в сделку</h2><ul className="text-sm">{deal.items.map((i) => <li key={i.id}>{L(i.portion)} — <Money v={i.amount} /> <span className="muted">(из КП «{L(i.offer.offer_scope)}», версия {i.offer.version})</span></li>)}</ul>
        <p className="mt-2 text-xs text-slate-500">Как проходит сделка: заказчик оплачивает этап → деньги удерживаются платформой (эскроу) → исполнитель выполняет и сдаёт этап → заказчик проверяет по чек-листу и принимает → деньги уходят исполнителю, формируется акт, который подписывают обе стороны.</p></div>
      {deal.milestones.map((m) => { const hold = m.escrow_holds[0]; const gate = gates[m.id]; const disp = m.disputes.filter((d) => ["open", "in_review"].includes(d.status)); const penalty = computePenalty(m, deal.penalty_pct_per_day); return <div key={m.id} className="card"><div className="flex justify-between"><h3 className="font-semibold">{m.order_index + 1}. {m.name} — <Money v={m.amount} /></h3><div><Badge s={m.status} /> {hold && <Badge s={hold.status}>эскроу: {hold.status}{hold.blocked_by_dispute_id ? " 🔒" : ""}</Badge>}</div></div>
        <p className="muted text-xs">срок <Dt d={m.due_date} />{penalty.gt(0) && m.status !== "accepted" ? ` · просрочка, расчётная пеня ${penalty} ₸` : ""}{m.accepted_amount ? ` · принято ${m.accepted_amount}` : ""}</p>
        <div className="mt-2 flex flex-wrap gap-2">
          {isBuyer && m.status === "pending" && <form action={D.payMilestoneAction}><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="milestone_id" value={m.id} /><button className="btn-primary">Оплатить этап (демо-оплата)</button><span className="ml-2 text-xs text-slate-500">деньги будут удержаны платформой до вашей приёмки</span></form>}
          {isSeller && ["funded"].includes(m.status) && !deal.work_started_at && <form action={D.startWorkAction}><input type="hidden" name="deal_id" value={id} /><button className="btn-secondary">Начать работы</button></form>}
          {isSeller && ["funded", "in_progress"].includes(m.status) && <form action={D.submitMilestoneAction}><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="milestone_id" value={m.id} /><button className="btn-primary">Сдать этап</button></form>}
          {(isBuyer || isAdmin) && ["submitted", "in_progress", "funded"].includes(m.status) && <form action={D.acceptMilestoneAction} className="flex items-center gap-1"><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="milestone_id" value={m.id} /><input className="input w-36" name="accepted_amount" type="number" placeholder="сумма, если частично" title={`Оставьте пустым, чтобы принять полностью (${m.amount} ₸)`} /><button className="btn-primary" disabled={disp.length > 0}>{disp.length ? "Принять (заблокировано спором)" : "Принять этап"}</button></form>}
          {isAdmin && hold?.status === "held" && <form action={D.releaseEscrowAction}><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="milestone_id" value={m.id} /><button className="btn-danger">Раскрыть эскроу (админ)</button></form>}
          {(isBuyer || isSeller || isSupervisor) && !disp.length && ["funded", "in_progress", "submitted"].includes(m.status) && <form action={D.openDisputeAction} className="flex gap-1"><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="milestone_id" value={m.id} /><select className="input w-28" name="category"><option value="quality">качество</option><option value="deadline">сроки</option><option value="payment">оплата</option><option value="other">другое</option></select><input className="input w-48" name="reason" placeholder="Причина спора" required /><button className="btn-danger">Открыть спор</button></form>}
        </div>
        {gate.items.length > 0 && <details className="mt-2 text-sm" open={m.status === "submitted"}><summary className="cursor-pointer">Чек-лист приёмки ({gate.results.filter((r) => r.checked).length}/{gate.items.length}){gate.missing.length ? ` — пунктов с обязательным фото без фото: ${gate.missing.length}` : ""}</summary><p className="text-xs text-slate-500">Пункты с 📷* — критичные: их нельзя принять без фотографии. Без них кнопка «Принять этап» не сработает.</p><table className="table mt-1">{gate.items.map((it) => { const r = gate.results.find((x) => x.checklist_item_id === it.id); return <tr key={it.id}><td>{it.item_text}{it.photo_required ? <span className="ml-1 text-red-600" title="критичный: требуется фото">📷*</span> : null}</td><td>{r?.checked ? "✔" : "—"}{r?.photo_url ? <a className="ml-1 text-brand-600" href={r.photo_url}>фото</a> : ""}</td><td>{(isBuyer || isSupervisor || isAdmin) && <form action={D.checklistAction} className="flex gap-1"><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="milestone_id" value={m.id} /><input type="hidden" name="item_id" value={it.id} /><label className="text-xs"><input type="checkbox" name="checked" defaultChecked={r?.checked} /> выполнено</label><input type="file" name="photo" accept="image/*" className="w-44 text-xs" /><input type="hidden" name="photo_url" value={r?.photo_url ?? ""} /><button className="btn-secondary text-xs">Сохранить</button></form>}</td></tr>; })}</table></details>}
      </div>; })}
      <div className="card"><h2 className="h2 mb-2">Акты</h2>{deal.acts.map((a) => <div key={a.id} className="border-t border-slate-100 py-1 text-sm"><b>{L(a.act_type)}</b> <Badge s={a.status} /> · <a className="text-brand-600" href={a.file_url ?? "#"} target="_blank">открыть документ</a> · заказчик: {a.signed_by_buyer_at ? "✓" : "—"} · исполнитель: {a.signed_by_seller_at ? "✓" : "—"}{a.act_type === "supervisor_conclusion" ? <> · технадзор: {a.signed_by_supervisor_at ? "✓" : "—"}</> : null} · подписать до <Dt d={a.sign_deadline_at} />
        {a.status !== "signed" && ((isBuyer && !a.signed_by_buyer_at) || (isSeller && !a.signed_by_seller_at) || (isSupervisor && a.act_type === "supervisor_conclusion" && !a.signed_by_supervisor_at)) && <form action={D.signActAction} className="inline"><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="act_id" value={a.id} /><button className="btn-secondary ml-2 text-xs">Подписать (ЭЦП-мок)</button></form>}</div>)}{!deal.acts.length && <p className="muted">Акт формируется автоматически при приёмке этапа. Платформа акты не подписывает — только стороны.</p>}
        {isSupervisor && <form action={D.supervisorActAction} className="mt-3 flex gap-2"><input type="hidden" name="deal_id" value={id} /><select className="input w-48" name="milestone_id"><option value="">по сделке</option>{deal.milestones.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><input className="input" name="conclusion" placeholder="Заключение технадзора" required /><button className="btn-primary">Сформировать и подписать</button></form>}</div>
      <div className="card"><h2 className="h2 mb-2">Споры</h2>{deal.disputes.map((d) => <div key={d.id} className="border-t border-slate-100 py-1 text-sm"><Badge s={d.status} /> <b>{L(d.category)}</b> · {d.reason} <span className="muted"><Dt d={d.created_at} /></span>{d.resolution && <div className="text-slate-600">Решение: {d.resolution}</div>}
        {isAdmin && ["open", "in_review"].includes(d.status) && <form action={D.resolveDisputeAction} className="mt-1 flex flex-wrap gap-1"><input type="hidden" name="dispute_id" value={d.id} /><input type="hidden" name="back" value={`/deals/${id}`} /><input className="input w-64" name="resolution" placeholder="Резолюция" required /><label className="text-xs"><input type="checkbox" name="release" /> раскрыть эскроу исполнителю</label><input className="input w-20" name="share" type="number" step="0.1" min={0} max={1} defaultValue={1} title="доля" /><button className="btn-primary" name="outcome" value="resolved">resolved</button><button className="btn-secondary" name="outcome" value="rejected">rejected</button></form>}</div>)}{!deal.disputes.length && <p className="muted">Споров нет</p>}</div>
      <div className="card"><h2 className="h2 mb-2">Гарантийные претензии</h2>{deal.warranty_claims.map((w) => <div key={w.id} className="border-t border-slate-100 py-1 text-sm"><Badge s={w.status} /> {w.description} <span className="muted"><Dt d={w.created_at} /></span>{(isSeller || isAdmin) && !["resolved", "rejected"].includes(w.status) && <form action={D.warrantyStatusAction} className="ml-2 inline"><input type="hidden" name="deal_id" value={id} /><input type="hidden" name="claim_id" value={w.id} /><button className="btn-secondary text-xs" name="status" value="in_progress">в работу</button> <button className="btn-secondary text-xs" name="status" value="resolved">решено</button> <button className="btn-secondary text-xs" name="status" value="rejected">отклонить</button></form>}</div>)}
        {isBuyer && <form action={D.warrantyAction} className="mt-2 flex gap-2"><input type="hidden" name="deal_id" value={id} /><input className="input" name="description" placeholder="Описание дефекта" required /><input className="input w-40" name="photo_url" placeholder="URL фото" /><button className="btn-secondary">Претензия</button></form>}</div>
    </div><div className="space-y-4">
      <div className="card"><h2 className="h2 mb-2">Платежи и эскроу</h2><ul className="text-sm">{deal.payments.map((p) => <li key={p.id}><Badge s={p.status} /> <Money v={p.amount} /> · {p.provider} {p.provider_ref ?? ""} · попыток {p.attempts}{p.last_error ? ` · ${p.last_error}` : ""}</li>)}{deal.escrow_holds.map((h) => <li key={h.id}>🔐 <Money v={h.amount} /> <Badge s={h.status} /> {h.provider_ref}{h.blocked_by_dispute_id ? " · заблокировано спором" : ""}</li>)}</ul>{!deal.payments.length && <p className="muted">Оплат ещё не было. {isBuyer ? "Нажмите «Оплатить этап» выше — это демо-оплата, деньги удерживаются платформой до приёмки." : "Ждём оплату этапа заказчиком — вы получите уведомление."}</p>}
        {isBuyer && !["completed", "cancelled"].includes(deal.status) && <form action={D.cancelDealAction} className="mt-2"><input type="hidden" name="deal_id" value={id} /><button className="btn-danger text-xs">Отменить сделку (cancel_policy)</button></form>}</div>
      <div className="card"><h2 className="h2 mb-2">Отзыв и оценки</h2>{deal.reviews.map((r) => <p key={r.id} className="text-sm">{"★".repeat(r.rating)} {r.text} <span className="muted">verified={String(r.verified)} · вес {r.weight.toFixed(2)}</span></p>)}
        {(isBuyer || isSupervisor) && !myReview && deal.status === "completed" && <form action={D.reviewAction} className="space-y-1"><input type="hidden" name="deal_id" value={id} /><Field label="Рейтинг"><select className="input" name="rating" defaultValue="5">{[5, 4, 3, 2, 1].map((n) => <option key={n} value={n}>{"★".repeat(n)}</option>)}</select></Field><textarea className="input" name="text" placeholder="Текст отзыва" rows={2} /><label className="block text-xs text-slate-500">Фото результата (попадёт в портфолио компании)<input type="file" name="photo" accept="image/*" className="block text-xs" /></label><button className="btn-primary">Оставить отзыв</button></form>}
        {(isBuyer || isSupervisor) && deal.status !== "completed" && !myReview && <p className="muted">Отзыв можно оставить после завершения сделки (в течение {config.reviewWindowDays} дней) — он будет помечен как верифицированный.</p>}
        {isSeller && <form action={D.rateAction} className="mt-2 flex gap-1"><input type="hidden" name="deal_id" value={id} /><select className="input w-24" name="rating" defaultValue="5">{[5, 4, 3, 2, 1].map((n) => <option key={n} value={n}>{n}★</option>)}</select><input className="input" name="text" placeholder="Оценка заказчика (двусторонний рейтинг)" /><button className="btn-secondary">Оценить</button></form>}</div>
    </div></div></div>;
}
