import Link from "next/link";
import { requireSession, requireRole } from "@/server/auth";
import { adminDashboard } from "@/server/services/admin";
import { prisma } from "@/server/db";
import { JOBS } from "@/server/jobs";
import { verifyChain } from "@/server/activity";
import { Badge, Dt, Flash, Money, FileLink } from "@/components/ui";
import { adminAction } from "@/server/actions/misc";
import { config } from "@/server/config";
import { L } from "@/lib/i18n";
import { resolveDisputeAction } from "@/server/actions/deals";

export default async function Admin({ searchParams }: { searchParams: Promise<{ error?: string; ok?: string }> }) {
  const s = await requireSession(); requireRole(s, "admin"); const sp = await searchParams;
  const d = await adminDashboard();
  const cats = await prisma.category.findMany();
  const boardReports = await prisma.boardReport.findMany({ where: { status: "open" }, orderBy: { created_at: "asc" } });
  const boardTargets = await Promise.all(boardReports.map(async (r) => ({ r, text: r.target_type === "post" ? (await prisma.boardPost.findUnique({ where: { id: r.target_id }, select: { title: true, body: true } }))?.title : (await prisma.boardReply.findUnique({ where: { id: r.target_id }, select: { body: true } }))?.body })));
  const [companies, reviewDisputes, log, chain, jobRuns, leadDisputes] = await Promise.all([prisma.company.findMany({ where: { role: { in: ["supplier", "contractor"] } }, orderBy: { name: "asc" } }), prisma.reviewDispute.findMany({ where: { status: "open" }, include: { review: true, company: true } }), prisma.activityLog.findMany({ orderBy: { created_at: "desc" }, take: 40 }), verifyChain(20000), prisma.activityLog.findMany({ where: { entity_type: "job" }, orderBy: { created_at: "desc" }, take: 14 }), prisma.activityLog.findMany({ where: { entity_type: "lead", action: "dispute_opened" }, orderBy: { created_at: "desc" }, take: 10 })]);
  const H = ({ v }: { v: string }) => <input type="hidden" name="action" value={v} />;
  return <div><h1 className="h1 mb-4">Админ / диспетчер</h1><Flash sp={sp} />
    <div className="grid gap-4 lg:grid-cols-2">
      <div className="card"><h2 className="h2 mb-2">Заявки без кандидатов (needs_dispatcher: {d.needsDispatcher.length})</h2>{d.needsDispatcher.map((r) => <form key={r.id} action={adminAction} className="flex flex-wrap items-center gap-1 border-t border-slate-100 py-1 text-sm"><H v="assign_lead" /><input type="hidden" name="request_id" value={r.id} /><Link className="text-brand-600" href={`/requests/${r.id}`}>{r.category.name}</Link> · {r.project.city} → <select className="input w-48" name="company_id">{companies.filter((c) => (c.categories_json as string[]).includes(r.category_id)).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}{!companies.some((c) => (c.categories_json as string[]).includes(r.category_id)) && <option value="">нет компаний в категории</option>}</select><input className="input w-20" name="price" type="number" defaultValue={0} /><button className="btn-primary text-xs">Назначить</button></form>)}{!d.needsDispatcher.length && <p className="muted">Пусто</p>}</div>
      <div className="card"><h2 className="h2 mb-2">Верификации на проверке ({d.pendingVerifications.length})</h2>{d.pendingVerifications.map((v) => <form key={v.id} action={adminAction} className="flex flex-wrap items-center gap-1 border-t border-slate-100 py-1 text-sm"><H v="verify" /><input type="hidden" name="verification_id" value={v.id} />{v.company.name} · {L(v.doc_type)}{v.category_id ? ` · ${cats.find((k) => k.id === v.category_id)?.name ?? ""}` : ""} <FileLink url={v.doc_url} label="документ" /> <input className="input w-36" name="valid_until" type="date" /><button className="btn-primary text-xs" name="status" value="verified">verified</button><button className="btn-secondary text-xs" name="status" value="rejected">rejected</button></form>)}{!d.pendingVerifications.length && <p className="muted">Пусто</p>}</div>
      <div className="card"><h2 className="h2 mb-2">Открытые споры ({d.openDisputes.length})</h2>{d.openDisputes.map((x) => <div key={x.id} className="border-t border-slate-100 py-1 text-sm"><Badge s={x.status} /> <b>{L(x.category)}</b> · {x.deal.seller.name} · <Link className="text-brand-600" href={`/deals/${x.deal_id}`}>сделка</Link> — {x.reason}{x.milestone_id ? " · 🔒 эскроу заблокирован" : ""}
        <div className="mt-1 flex flex-wrap gap-1">{x.status === "open" && <form action={adminAction}><H v="dispute_review" /><input type="hidden" name="dispute_id" value={x.id} /><button className="btn-secondary text-xs">В рассмотрение</button></form>}<form action={resolveDisputeAction} className="flex gap-1"><input type="hidden" name="dispute_id" value={x.id} /><input type="hidden" name="back" value="/admin" /><input className="input w-48" name="resolution" placeholder="Резолюция" required /><label className="text-xs"><input type="checkbox" name="release" /> раскрыть</label><input className="input w-16" name="share" type="number" step="0.1" defaultValue={1} /><button className="btn-primary text-xs" name="outcome" value="resolved">resolved</button><button className="btn-secondary text-xs" name="outcome" value="rejected">rejected</button></form></div></div>)}{!d.openDisputes.length && <p className="muted">Пусто</p>}</div>
      <div className="card"><h2 className="h2 mb-2">Выплаты ({d.pendingPayouts.length})</h2>{d.pendingPayouts.map((p) => <form key={p.id} action={adminAction} className="flex items-center gap-1 border-t border-slate-100 py-1 text-sm"><H v="payout" /><input type="hidden" name="payout_id" value={p.id} />{p.company.name} · <Money v={p.amount} /> · {p.bank_account} <Badge s={p.status} />{p.status === "pending" && <button className="btn-primary text-xs" name="op" value="approve">approve</button>}{p.status === "approved" && <button className="btn-primary text-xs" name="op" value="complete">complete</button>}<button className="btn-secondary text-xs" name="op" value="reject">reject</button></form>)}{!d.pendingPayouts.length && <p className="muted">Пусто</p>}
        <h2 className="h2 mb-2 mt-3">Платежи в retry/pending ({d.retryPayments.length})</h2>{d.retryPayments.map((p) => <p key={p.id} className="text-sm"><Badge s={p.status} /> <Money v={p.amount} /> {p.provider} · попыток {p.attempts} · {p.last_error}</p>)}</div>
      <div className="card"><h2 className="h2 mb-2">Soft-ban компаний</h2>{d.softBanned.map((c) => <form key={c.id} action={adminAction} className="flex items-center gap-1 border-t border-slate-100 py-1 text-sm"><H v="soft_ban" /><input type="hidden" name="company_id" value={c.id} /><input type="hidden" name="until" value="" />{c.name} до <Dt d={c.soft_banned_until} /> — {c.soft_ban_reason} <button className="btn-secondary text-xs">Снять</button></form>)}
        <form action={adminAction} className="mt-2 flex flex-wrap gap-1 text-sm"><H v="soft_ban" /><select className="input w-48" name="company_id">{companies.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input w-36" name="until" type="date" required /><input className="input w-40" name="reason" placeholder="Причина" /><button className="btn-danger text-xs">Поставить бан</button></form>
        <h2 className="h2 mb-2 mt-3">Оспаривания отзывов ({reviewDisputes.length})</h2>{reviewDisputes.map((r) => <form key={r.id} action={adminAction} className="flex flex-wrap items-center gap-1 border-t border-slate-100 py-1 text-sm"><H v="review_dispute" /><input type="hidden" name="review_dispute_id" value={r.id} />{r.company.name}: «{r.review.text?.slice(0, 40)}» — {r.reason} <label className="text-xs"><input type="checkbox" name="hide" /> скрыть отзыв</label><button className="btn-primary text-xs" name="outcome" value="resolved">resolved</button><button className="btn-secondary text-xs" name="outcome" value="rejected">rejected</button></form>)}
        <h2 className="h2 mb-2 mt-3">Жалобы на доске обсуждений ({boardReports.length})</h2>{boardTargets.map(({ r, text }) => <form key={r.id} action={adminAction} className="flex flex-wrap items-center gap-1 border-t border-slate-100 py-1 text-sm"><H v="board_report" /><input type="hidden" name="report_id" value={r.id} />{L(r.target_type)}: «{(text ?? "[удалено]").slice(0, 60)}» — {r.reason} <input className="input w-40" name="resolution" placeholder="Комментарий" /><button className="btn-primary text-xs" name="outcome" value="resolved">удалить сообщение</button><button className="btn-secondary text-xs" name="outcome" value="rejected">оставить</button></form>)}{!boardReports.length && <p className="muted">Пусто</p>}
        <h2 className="h2 mb-2 mt-3">Запросы возврата лидов</h2>{leadDisputes.map((l) => <form key={l.id} action={adminAction} className="flex items-center gap-1 text-sm"><H v="refund_lead" /><input type="hidden" name="lead_id" value={l.entity_id} />лид {l.entity_id.slice(-6)} · {(l.meta_json as { reason?: string })?.reason} <button className="btn-secondary text-xs">Вернуть</button></form>)}</div>
      <div className="card"><h2 className="h2 mb-2">Фоновые задачи (планировщик {config.schedulerEnabled ? "включён" : "выключен — запускайте вручную кнопками"})</h2><div className="flex flex-wrap gap-1">{Object.keys(JOBS).map((j) => <form key={j} action={adminAction}><H v="job" /><input type="hidden" name="job" value={j} /><button className="btn-secondary text-xs">▶ {j}</button></form>)}</div><ul className="mt-2 text-xs text-slate-500">{jobRuns.map((j) => <li key={j.id}>{j.created_at.toLocaleTimeString("ru-RU")} {j.entity_id}: {JSON.stringify(j.meta_json)?.slice(0, 80)}</li>)}</ul></div>
    </div>
    <div className="card mt-4"><h2 className="h2 mb-2">activity_log (append-only, hash-цепочка: {chain.ok ? `✓ ${chain.checked} записей` : `✗ сломана на ${chain.brokenAt}`})</h2><table className="table text-xs"><tbody>{log.map((l) => <tr key={l.id}><td>{l.created_at.toLocaleString("ru-RU")}</td><td>{l.entity_type}</td><td>{l.entity_id.slice(-8)}</td><td><b>{l.action}</b></td><td className="max-w-md truncate">{JSON.stringify(l.meta_json)?.slice(0, 100)}</td><td className="text-slate-300">{l.hash.slice(0, 8)}</td></tr>)}</tbody></table></div></div>;
}
