import Link from "next/link";
import { requireSession } from "@/server/auth";
import { prisma } from "@/server/db";
import { compareOffers } from "@/server/services/offers";
import { Badge, Dt, Flash, Money } from "@/components/ui";
import { createDealAction, cancelRequestAction, openThreadAction } from "@/server/actions/buyer";
import { STATUS_RU, L } from "@/lib/i18n";

export default async function RequestPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; ok?: string }> }) {
  const { id } = await params; const sp = await searchParams; const s = await requireSession();
  const req = await prisma.request.findUnique({ where: { id }, include: { project: true, category: true, template: { include: { parameters: { orderBy: { order_index: "asc" } } } }, leads: { include: { company: true } }, threads: true, deals: true, links_as_linked: { include: { primary: { include: { category: true, deals: true } } } }, links_as_primary: { include: { linked: { include: { category: true } } } } } });
  if (!req) return <p>Не найдено</p>;
  const cids = s.user.companies.map((c) => c.id);
  const isBuyer = req.project.owner_id === s.user.id || (req.project.company_id ? cids.includes(req.project.company_id) : false) || s.user.roles.includes("admin");
  const myLead = req.leads.find((l) => cids.includes(l.company_id));
  if (!isBuyer && !myLead) return <p className="text-red-700">Нет доступа</p>;
  const { rows } = await compareOffers(id);
  const values = req.values_json as Record<string, unknown>;
  const logs = await prisma.activityLog.findMany({ where: { entity_type: "request", entity_id: id, action: { startsWith: "match" } }, orderBy: { created_at: "asc" } });
  const canPick = isBuyer && ["published", "needs_dispatcher"].includes(req.status);
  return <div><Flash sp={sp} />
    <div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h1 className="h1">{req.category.name} <Badge s={req.status} /></h1><p className="muted">Объект <Link className="text-brand-600" href={`/projects/${req.project_id}`}>{req.project.name}</Link> · {L(req.mode)} · шаблон v{req.template_version} · до <Dt d={req.expires_at} /></p></div>
      {canPick && <form action={cancelRequestAction} className="flex gap-1"><input type="hidden" name="request_id" value={id} /><select className="input w-40" name="reason"><option value="cancelled">отменить</option><option value="duplicate">дубль (вернуть лиды)</option></select><button className="btn-secondary">Отменить</button></form>}</div>
    {req.links_as_linked.map((l) => <p key={l.id} className="mb-3 rounded bg-brand-50 p-2 text-sm">Доставка для заявки «{l.primary.category.name}»{l.primary.deals[0] ? <> — <Link className="text-brand-600" href={`/deals/${l.primary.deals[0].id}`}>сделка по материалу</Link></> : null}.</p>)}
    {req.links_as_primary.map((l) => <p key={l.id} className="mb-3 text-sm">Связанная заявка на доставку: <Link className="text-brand-600" href={`/requests/${l.linked_request_id}`}>{l.linked.category.name}</Link></p>)}
    {(values._from_pitch as string | undefined) && <p className="mb-3 rounded bg-amber-50 p-2 text-sm text-amber-900">Заявка создана из встречного предложения поставщика: «{String(values._from_pitch)}». Параметры ниже заполнены условно — уточните детали в чате с поставщиком.</p>}
    <div className="grid gap-4 lg:grid-cols-3">
      <div className="lg:col-span-2 space-y-4">
        <div className="card"><h2 className="h2 mb-2">Сравнение коммерческих предложений (КП) — {rows.length}</h2>
          {rows.length ? <form action={createDealAction}><input type="hidden" name="request_id" value={id} /><div className="overflow-x-auto"><table className="table"><thead><tr><th>Компания</th><th>Объём КП</th><th>Материал</th><th>Работа</th><th>Доставка</th><th>Срок</th><th>Гарантия</th><th>ИТОГО</th><th>Соотв.</th><th>Рейтинг</th><th>Лицензия</th><th>Статус</th>{canPick && <th>Выбор</th>}</tr></thead><tbody>{rows.map((r) => <tr key={r.offer_id} className={r.status === "accepted" ? "bg-green-50" : ""}><td><Link className="text-brand-600" href={`/catalog/${r.slug}`}>{r.company}</Link><div className="text-xs text-slate-400">v{r.version}{r.suspicious_cheap ? " · ⚠ подозрительно дёшево" : ""}</div></td><td className="text-xs">{L(r.scope)}</td><td><Money v={r.material} /></td><td><Money v={r.work} /></td><td><Money v={r.delivery} /></td><td>{r.days} дн.</td><td className="text-xs">{r.warranty ?? "—"}</td><td className="font-semibold"><Money v={r.total} /></td><td>{r.matches_params ? "✓" : <span title={r.mismatch_notes ?? ""}>✗</span>}</td><td>★{r.rating.toFixed(1)}</td><td>{r.licensed === null ? "—" : r.licensed ? "✓" : "✗"}</td><td><Badge s={r.status} /></td>
            {canPick && <td>{r.status === "sent" ? <div className="flex flex-col gap-0.5 text-xs">{r.material.gt(0) && <label><input type="checkbox" name="select" value={`${r.offer_id}:material`} /> материал</label>}{r.work.gt(0) && <label><input type="checkbox" name="select" value={`${r.offer_id}:install`} /> монтаж</label>}{r.delivery.gt(0) && <label><input type="checkbox" name="select" value={`${r.offer_id}:delivery`} /> доставка</label>}</div> : null}</td>}</tr>)}</tbody></table></div>
            {canPick && <div className="mt-3 flex items-center gap-3"><button className="btn-primary">Создать сделку из выбранного</button><span className="text-xs text-slate-400">Можно выбрать части из разных КП (разделённый выбор). Остальные КП получат статус «не выбрано».</span></div>}</form> : <p className="muted">{req.leads.length ? `Заявка отправлена ${req.leads.length} поставщикам. Когда они ответят, предложения появятся здесь и во «Входящих» — сравните и выберите исполнителя.` : req.status === "needs_dispatcher" ? "Подходящих поставщиков в вашей зоне пока не нашлось — заявка передана диспетчеру платформы, он назначит исполнителя вручную." : "Предложений пока нет."}</p>}
          {rows.some((r) => r.items?.length) && <details className="mt-3 text-sm"><summary className="cursor-pointer">Позиции материалов</summary>{rows.map((r) => r.items?.length ? <div key={r.offer_id} className="mt-1"><b>{r.company}</b><ul className="ml-4 list-disc">{r.items.map((it, i) => <li key={i}>{it.name} — {it.qty} {it.unit} × <Money v={it.price} /></li>)}</ul></div> : null)}</details>}
        </div>
        {isBuyer && <div className="card"><h2 className="h2 mb-2">Кому ушла заявка (исходящие)</h2><table className="table"><thead><tr><th>Компания</th><th>Как получила</th><th>Статус</th><th>Чат</th></tr></thead><tbody>{req.leads.map((l) => <tr key={l.id}><td><Link className="text-brand-600" href={`/catalog/${l.company.public_slug}`}>{l.company.name}</Link></td><td>{L(l.origin)}</td><td><Badge s={l.status}>{l.status === "offered" ? "ещё не открыла заявку" : l.status === "purchased" ? "изучает заявку" : l.status === "declined" ? "отказалась" : STATUS_RU[l.status]}</Badge></td><td>{l.status === "purchased" ? <form action={openThreadAction}><input type="hidden" name="request_id" value={id} /><input type="hidden" name="seller_id" value={l.company_id} /><button className="btn-secondary text-xs">Открыть чат</button></form> : null}</td></tr>)}</tbody></table>{!req.leads.length && <p className="muted">Лидов нет{req.status === "needs_dispatcher" ? " — заявка передана диспетчеру" : ""}.</p>}</div>}
        {myLead && !isBuyer && <div className="card"><h2 className="h2 mb-2">Ваш лид</h2><p className="text-sm">Статус: <Badge s={myLead.status} /> · {L(myLead.origin)} · цена лида {myLead.price.toString()} ₸</p><div className="mt-2 flex gap-2">{myLead.status === "purchased" && <><Link href={`/supplier/offers/new?request=${id}`} className="btn-primary">Отправить КП</Link><form action={openThreadAction}><input type="hidden" name="request_id" value={id} /><input type="hidden" name="seller_id" value={myLead.company_id} /><button className="btn-secondary">Чат с заказчиком</button></form></>}<Link href="/supplier/leads" className="btn-secondary">К лидам</Link></div></div>}
        {isBuyer && logs.length > 0 && <details className="card text-sm"><summary className="cursor-pointer font-semibold">Объяснимость матчинга ({logs.length} прогонов)</summary>{logs.map((l) => { const m = l.meta_json as { candidates?: { name: string; included: boolean; reason: string; distance_km?: number; score?: number }[]; radius_multiplier?: number; multiplier?: number } | null; return <div key={l.id} className="mt-2 border-t border-slate-100 pt-1"><b>{l.action}</b> <span className="muted"><Dt d={l.created_at} /> {m?.radius_multiplier ? `радиус ×${m.radius_multiplier}` : ""}</span><ul className="ml-4 list-disc">{m?.candidates?.map((c, i) => <li key={i} className={c.included ? "text-green-700" : "text-slate-500"}>{c.name}: {c.reason}{c.distance_km != null ? ` (${c.distance_km.toFixed(0)} км)` : ""}{c.score != null ? ` score ${c.score}` : ""}</li>)}</ul></div>; })}</details>}
      </div>
      <div className="space-y-4"><div className="card"><h2 className="h2 mb-2">Параметры заявки</h2><dl className="text-sm">{req.template.parameters.map((p) => <div key={p.id} className="flex justify-between gap-2 border-b border-slate-50 py-0.5"><dt className="muted">{p.label}</dt><dd className="text-right">{Array.isArray(values[p.key]) ? (values[p.key] as string[]).join(", ") : typeof values[p.key] === "boolean" ? (values[p.key] ? "да" : "нет") : String(values[p.key] ?? "—")}{p.unit ? " " + p.unit : ""}</dd></div>)}</dl>{req.ai_extracted_json ? <p className="mt-2 text-xs text-slate-400">Часть значений предзаполнена AI-разбором и подтверждена заказчиком.</p> : null}</div>
        {req.deals.length > 0 && <div className="card"><h2 className="h2 mb-1">Сделки</h2><ul className="text-sm">{req.deals.map((d) => <li key={d.id}><Link className="text-brand-600" href={`/deals/${d.id}`}>{d.id.slice(-8)}</Link> · <Money v={d.amount} /> · {STATUS_RU[d.status] ?? d.status}</li>)}</ul></div>}
      </div>
    </div></div>;
}
