import Link from "next/link";
import { requireSession } from "@/server/auth";
import { assertProjectAccess } from "@/server/services/projects";
import { prisma } from "@/server/db";
import { Badge, Dt, Field, Flash, Money, FileLink } from "@/components/ui";
import { updateProjectAction, stageProgressAction, addLabReportAction } from "@/server/actions/buyer";
import { LAB_DISCLAIMER } from "@/server/services/timeline";
import { L } from "@/lib/i18n";
import { config } from "@/server/config";

export default async function ProjectPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; ok?: string }> }) {
  const { id } = await params; const sp = await searchParams; const s = await requireSession();
  await assertProjectAccess(id, s.user.id);
  const p = await prisma.project.findUniqueOrThrow({ where: { id }, include: { children: true, parent: true, files: true, lab_reports: true, stages: { orderBy: { order_index: "asc" }, include: { schedule: true } }, requests: { include: { category: true, offers: true, leads: true }, orderBy: { created_at: "desc" } }, pitches: { include: { company: true, category: true } } } });
  const cats = await prisma.category.findMany({ orderBy: { order_index: "asc" } });
  const applicable = cats.filter((c) => (c.object_types_json as string[]).includes(p.object_type));
  const catName = (cid: string | null) => cats.find((c) => c.id === cid)?.name;
  return <div><Flash sp={sp} />
    <div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h1 className="h1">{p.name}</h1><p className="muted">{L(p.object_type)}{p.construction_type ? ` (${L(p.construction_type)})` : ""} · {p.city}{p.district ? ", " + p.district : ""} · {p.address} · {p.area ?? "?"} м² · {p.floors ?? "?"} эт.{p.parent ? <> · часть <Link className="text-brand-600" href={`/projects/${p.parent.id}`}>{p.parent.name}</Link></> : null}</p></div><Badge s={p.status} /></div>
    <div className="grid gap-4 lg:grid-cols-3">
      <div className="space-y-4 lg:col-span-2">
        <div className="card"><div className="mb-2 flex items-center justify-between"><h2 className="h2">Заявки</h2><div className="flex flex-wrap gap-1">{applicable.map((c) => <Link key={c.id} href={`/projects/${id}/requests/new?category=${c.id}`} className="btn-secondary text-xs">+ {c.name}</Link>)}</div></div>
          {p.requests.length ? <table className="table"><thead><tr><th>Категория</th><th>Режим</th><th>Статус</th><th>Лидов</th><th>КП</th><th>Шаблон</th></tr></thead><tbody>{p.requests.map((r) => <tr key={r.id}><td><Link href={`/requests/${r.id}`} className="text-brand-600">{r.category.name}</Link></td><td>{L(r.mode)}</td><td><Badge s={r.status} /></td><td>{r.leads.length}</td><td>{r.offers.filter((o) => o.status === "sent").length}/{r.offers.length}</td><td className="muted">v{r.template_version}</td></tr>)}</tbody></table> : <p className="muted">Заявок ещё нет. Нажмите нужную категорию работ выше — откроется форма с параметрами, после публикации подходящие поставщики получат заявку сразу и пришлют предложения.</p>}</div>
        <div className="card"><h2 className="h2 mb-2">Этапы и предиктивный график</h2><table className="table"><thead><tr><th>Этап</th><th>План</th><th>Понадобится</th><th>Прогресс</th></tr></thead><tbody>{p.stages.map((st) => { const sc = st.schedule[0]; return <tr key={st.id}><td>{st.order_index}. {st.name}</td><td className="muted"><Dt d={sc?.planned_start} /> — <Dt d={sc?.planned_end} />{sc?.actual_date ? <> ✓ <Dt d={sc.actual_date} /></> : null}</td><td className="muted">{catName(sc?.predicted_next_need_category_id ?? null) ?? "—"}{sc?.notified_at ? " 🔔" : ""}</td><td><form action={stageProgressAction} className="flex items-center gap-1"><input type="hidden" name="project_id" value={id} /><input type="hidden" name="stage_id" value={st.id} /><input className="input w-16" name="progress" type="number" min={0} max={100} defaultValue={st.progress_pct} /><button className="btn-secondary text-xs">ок</button></form></td></tr>; })}</tbody></table><p className="mt-1 text-xs text-slate-400">Планировщик уведомит за {p.stages[0]?.schedule[0]?.lead_time_days ?? 14} дн. до прогнозной даты следующей потребности. Завершение этапа (100%) сдвигает график по факту.</p></div>
        {p.pitches.length > 0 && <div className="card"><h2 className="h2 mb-2">Встречные предложения по объекту</h2><ul className="text-sm">{p.pitches.map((x) => <li key={x.id}><b>{x.company.name}</b> · {x.category.name} · <Badge s={x.status} /> — {x.message} {x.price_estimate ? <Money v={x.price_estimate} /> : null}</li>)}</ul><Link href="/inbox" className="muted">Ответить во входящих →</Link></div>}
        <div className="card"><h2 className="h2 mb-2">Лабораторные отчёты</h2><p className="mb-2 text-xs text-amber-700">{LAB_DISCLAIMER}</p>{p.lab_reports.map((l) => <div key={l.id} className="border-t border-slate-100 py-1 text-sm"><b>{l.lab_name}</b> · {l.report_type} · <Dt d={l.created_at} /> {l.verified ? <Badge s="verified" /> : <span className="muted">(не проверен)</span>}<div>{l.verdict_summary}</div><FileLink url={l.file_url} label="отчёт" /></div>)}
          <form action={addLabReportAction} className="mt-2 grid gap-2 sm:grid-cols-4"><input type="hidden" name="project_id" value={id} /><input className="input" name="lab_name" placeholder="Лаборатория" required /><select className="input" name="report_type"><option value="concrete">бетон</option><option value="soil">грунт</option><option value="water">вода</option><option value="electrical">электроизмерения</option><option value="other">другое</option></select><input className="input" name="verdict_summary" placeholder="Краткий вердикт" /><input type="file" name="file" className="text-xs" /><button className="btn-secondary">Добавить</button></form></div>
        <div className="card"><h2 className="h2 mb-2">Файлы</h2><ul className="text-sm">{p.files.map((f) => <li key={f.id}>{L(f.type)}: <FileLink url={f.url} label={f.name ?? "файл"} /> {f.validated ? "✓" : ""}</li>)}</ul><form action={`/api/projects/${id}/files`} method="post" encType="multipart/form-data" className="mt-2 flex gap-2"><select className="input w-32" name="type"><option value="plan">план</option><option value="photo">фото</option><option value="document">документ</option><option value="voice">голос</option></select><input type="file" name="file" className="text-sm" required /><button className="btn-secondary">Загрузить</button></form><p className="mt-1 text-xs text-slate-400">Проверка формата и размера (до {config.uploadMaxMb} МБ) на бэкенде.</p></div>
      </div>
      <div className="space-y-4">
        <div className="card"><h2 className="h2 mb-2">Регуляторный блок</h2><dl className="grid grid-cols-2 gap-1 text-sm"><dt className="muted">Сейсмичность</dt><dd>{p.seismicity} баллов</dd><dt className="muted">Уровень ответственности</dt><dd>{p.responsibility_level}</dd><dt className="muted">Разрешение на стр-во</dt><dd>{p.needs_permit ? "требуется" : "уведомительный порядок"}</dd><dt className="muted">Экспертиза проекта</dt><dd>{p.needs_expertise ? "требуется" : "нет"}</dd><dt className="muted">Технадзор</dt><dd>{p.needs_tech_supervision ? "обязателен" : "по желанию"}</dd><dt className="muted">Назначение земли</dt><dd>{p.land_purpose ?? "—"}</dd><dt className="muted">Ввод в эксплуатацию</dt><dd>{L(p.commissioning_status)}</dd></dl><p className="mt-2 text-xs text-slate-400">Рассчитано по матрице regulatory_rules; не является юридическим заключением.</p></div>
        <form action={updateProjectAction} className="card space-y-2 text-sm"><input type="hidden" name="id" value={id} /><h2 className="h2">Настройки объекта</h2>
          <label className="block"><input type="checkbox" name="open_to_pitches" defaultChecked={p.open_to_pitches} /> Виден на карте (встречные предложения)</label>
          <div className="grid grid-cols-2 gap-2"><Field label="Бюджет от"><input className="input" name="budget_min" defaultValue={p.budget_min?.toString()} /></Field><Field label="до"><input className="input" name="budget_max" defaultValue={p.budget_max?.toString()} /></Field></div>
          <div className="flex flex-wrap gap-2">{[["tu_electric", "ТУ эл."], ["tu_gas", "ТУ газ"], ["tu_water", "ТУ вода"], ["tu_sewer", "ТУ канал."], ["tu_heat", "ТУ тепло"]].map(([n, l]) => <label key={n}><input type="checkbox" name={n} defaultChecked={(p as unknown as Record<string, boolean>)[n]} /> {l}</label>)}</div>
          <Field label="Статус"><select className="input" name="status" defaultValue={p.status}>{["draft", "active", "paused", "completed", "archived"].map((x) => <option key={x} value={x}>{L(x)}</option>)}</select></Field>
          <Field label="Ввод в эксплуатацию"><select className="input" name="commissioning_status" defaultValue={p.commissioning_status}>{["not_started", "in_progress", "commissioned"].map((x) => <option key={x} value={x}>{L(x)}</option>)}</select></Field>
          <button className="btn-primary">Сохранить</button></form>
        {p.children.length > 0 && <div className="card"><h2 className="h2 mb-1">Корпуса / очереди</h2><ul className="text-sm">{p.children.map((c) => <li key={c.id}><Link className="text-brand-600" href={`/projects/${c.id}`}>{c.name}</Link></li>)}</ul></div>}
      </div>
    </div></div>;
}
