import { requireSession } from "@/server/auth";
import { prisma } from "@/server/db";
import { Field, Flash } from "@/components/ui";
import { profileAction, registerCompanyAction } from "@/server/actions/misc";
import Link from "next/link";

export default async function Settings({ searchParams }: { searchParams: Promise<{ error?: string; ok?: string }> }) {
  const s = await requireSession(); const sp = await searchParams;
  const [u, regions, referrals] = await Promise.all([prisma.user.findUniqueOrThrow({ where: { id: s.user.id }, include: { device_tokens: true, phone_changes: true, consents: true } }), prisma.region.findMany({ orderBy: { name: "asc" } }), prisma.user.count({ where: { referred_by: s.user.id } })]);
  return <div className="mx-auto max-w-3xl space-y-4"><h1 className="h1">Настройки</h1><Flash sp={sp} />
    <form action={profileAction} className="card grid gap-3 sm:grid-cols-2"><h2 className="h2 sm:col-span-2">Профиль</h2><Field label="Имя"><input className="input" name="name" defaultValue={u.name ?? ""} /></Field><Field label="Телефон" hint="Смена фиксируется в phone_change_log"><input className="input" name="phone" defaultValue={u.phone} /></Field><Field label="Email"><input className="input" name="email" defaultValue={u.email ?? ""} /></Field><Field label="Альтернативный email (восстановление)"><input className="input" name="alt_email" defaultValue={u.alt_email ?? ""} /></Field><Field label="Push-токен устройства (device_tokens)"><input className="input" name="device_token" placeholder="fcm-token…" /></Field><Field label="Платформа"><select className="input" name="platform"><option>web</option><option>ios</option><option>android</option></select></Field>
      <div className="sm:col-span-2 flex flex-wrap items-center gap-3"><button className="btn-primary">Сохранить</button><span className="muted">Реферальный код: <code className="rounded bg-slate-100 px-1">{u.referral_code}</code> · приглашено: {referrals} · устройств: {u.device_tokens.length} · согласий: {u.consents.length}</span></div></form>
    <div className="card flex flex-wrap items-center gap-3"><form action="/api/auth/logout-all" method="post"><button className="btn-danger">Выйти со всех устройств</button></form><span className="muted">Инвалидирует все выданные JWT (token_version++).</span><Link href="/settings/notifications" className="btn-secondary">Уведомления</Link></div>
    <div className="card"><h2 className="h2 mb-1">Мои компании</h2><ul className="text-sm">{s.user.companies.map((c) => <li key={c.id}>{c.name} — {c.role} ({c.permission}) {c.role !== "buyer" && <Link className="text-brand-600" href="/supplier/settings">настройки поставщика →</Link>}</li>)}</ul></div>
    <form action={registerCompanyAction} className="card grid gap-3 sm:grid-cols-2"><h2 className="h2 sm:col-span-2">Зарегистрировать юрлицо / ИП</h2><Field label="Название"><input className="input" name="name" required /></Field><Field label="Форма"><select className="input" name="legal_type"><option value="ip">ИП</option><option value="too">ТОО</option><option value="self_employed">Самозанятый</option></select></Field><Field label="БИН/ИИН (12 цифр)"><input className="input" name="bin" required pattern="\d{12}" /></Field><Field label="Роль компании"><select className="input" name="role"><option value="supplier">Поставщик</option><option value="contractor">Подрядчик</option><option value="buyer">Заказчик (стройкомпания)</option></select></Field><Field label="Масштаб"><select className="input" name="scale"><option value="individual">физлицо</option><option value="small">малый</option><option value="medium">средний</option><option value="large">крупный</option></select></Field><Field label="Налоговый статус (фискализация ЭСФ)"><select className="input" name="tax_status"><option value="non_vat">без НДС</option><option value="vat_payer">плательщик НДС</option><option value="simplified">упрощёнка</option></select></Field><Field label="Талон уведомления (ИП) / устав (ТОО) — URL загруженного файла"><input className="input" name="registration_doc_url" required placeholder="/uploads/..." /></Field><Field label="Банковский счёт (IBAN)"><input className="input" name="bank_account" /></Field><Field label="Регион"><select className="input" name="region">{regions.map((r) => <option key={r.code} value={r.code}>{r.name}</option>)}</select></Field><Field label="Город"><input className="input" name="city" /></Field><div className="grid grid-cols-3 gap-1"><Field label="Широта"><input className="input" name="lat" defaultValue="43.238" /></Field><Field label="Долгота"><input className="input" name="lng" defaultValue="76.945" /></Field><Field label="Радиус, км"><input className="input" name="radius" defaultValue="50" /></Field></div>
      <label className="text-sm sm:col-span-2"><input type="checkbox" name="consent" required /> Даю согласие на обработку персональных данных (consents)</label><div className="sm:col-span-2"><button className="btn-primary">Зарегистрировать</button></div></form>
    {u.phone_changes.length > 0 && <div className="card text-sm"><b>История смены номера</b><ul>{u.phone_changes.map((p) => <li key={p.id}>{p.old_phone} → {p.new_phone} ({p.changed_at.toLocaleDateString("ru-RU")})</li>)}</ul></div>}
  </div>;
}
